%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\MATLAB\sandbox\SpaceApp\PSP_Orbit_1.txt
%
% To extend the code to different selected data or a different text file, generate a function instead of a script.

% Auto-generated by MATLAB on 2022/10/01 13:37:00

function T = readTrajectory(filename)

%% Initialize variables.
startRow = 2;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%4f%8f%8f%8f%8f%8f%26f%20f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this code. If an error occurs for a different file, try regenerating the code from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post processing code is included. To generate code which works for unimportable data, select unimportable cells in a file and regenerate the script.

%% Create output variable
T = table(dataArray{1:end-1}, 'VariableNames', {'Year','Month','Day','Hour','Minute','Second','HCI_Xkm','HCI_Ykm','HCI_Zkm'});

%% Clear temporary variables
clearvars filename startRow formatSpec fileID dataArray ans;